dataset:
  data_dir: '/flexo/ComputationalMicroscopy/SpinningDisk/RawData/brainarchitecture/2018_10_02_MouseBrainSlice'
  # (str) The path of the folder that holds raw data

  samples: ['SM_2018_1002_1633_1', 'SM_2018_1002_1640_1']
  # (str or list) Acquisition folder(s) within the experiment folder to process

  positions: 'all'
  # (str or list) Positions within all of sample folders that are to be analyzed.
  ##   'all'
  ##   ['Pos1', 'Pos2', 'Pos3']
  ##   [['all'], ['Pos1', 'Pos2']], in which case all positions from Sample1 and Pos1 and Pos2 from Sample2 will be analyzed

  # The full path to the data is  data_dir/sample[n]/positions[m].

  z_slices: 'all'
  # (str, list, or range) Z slices to be analyzed.
  # The same set of z-slices will be analyzed for all positions and timepoints within a given sample
  # If the data do not contain z slices, leave out this parameter or set to 'all'
  ##   'all'
  ##   [0, 10, 20]
  ##   !!python/object/apply:builtins.range [10, 50, 5], in which case z slices in range(10,50,5) will be analyzed
  ##   [['all'], [0, 10, 20]], in which case all z slices from Sample1 and slices 0, 10, and 20 from Sample2 will be analyzed

  timepoints: 'all'
  # (str, list, or range) Timepoints to be analyzed.
  # The same set of timepoints will be analyzed for all positions and z-slices within a given sample
  # If the data do not contain z slices, leave out this parameter or set to 'all'
  ##   'all'
  ##   [0, 10, 20]
  ##   !!python/object/apply:builtins.range [10, 50, 5], in which case timepoints in range(10,50,5) will be analyzed
  ##   [['all'], [0, 10, 20]], in which case all timepoints from Sample1 and timepoints 0, 10, and 20 from Sample2 will be analyzed

  background: 'BG_2018_1002_1625_1'
  #(str or list) Background folder(s) within the experiment folder
  ##   a string, e.g. 'Background1', in which case all samples will be analyzed with the same background data;
  ##   a list, e.g. ['Background1', 'Background2'], of one background dataset per sample


  processed_dir: '/flexo/ComputationalMicroscopy/Projects/brainarchitecture'
  # (str) The path of the parent folder where the output will be saved

processing:
  output_channels: ['Brightfield_computed', 'Retardance', 'Orientation', 'Polarization']

  # (list) Any combination of the following values.
  ##    'Brightfield', 'Brightfield_computed', 'Retardance', 'Orientation', 'Polarization',
  ##    'Orientation_x', 'Orientation_y',
  ##    'Pol_State_0', 'Pol_State_1', 'Pol_State_2', 'Pol_State_3', 'Pol_State_4',
  ##    'Stokes_0', 'Stokes_1', 'Stokes_2', 'Stokes_3',
  ##    '405', '488', '568', '640',
  ##    'Retardance+Orientation', 'Polarization+Orientation',
  ##    'Transmission+Retardance+Orientation',
  ##    'Retardance+Fluorescence', 'Retardance+Fluorescence_all'

  circularity: 'rcp'
  # ('lcp' or 'rcp') the circularity of the analyzer looking from the detector's point of view.
  #    Changing this flag will flip the slow axis horizontally.

  background_correction: 'Input'
  # (str) Background correction method, one of the following
  ##   'None': no background correction will be performed
  ##   'Input': user-provided background will be removed from sample data
  ##   'Local_filter': sample is first corrected with background provided in dataset section. The residual background is further removed with 'rolling ball' background correction.
  ##   'Local_defocus': sample is corrected with out-of-focus image of the sample from 'BgDir_local' folder. The background images must have exactly same position indices as sample images.
  ##   'Auto': background for each sample position is chosen from the metadata generated by Micro-Manager.

  flatfield_correction: False
  # (bool) perform flat-field correction on fluorescence images if True

  azimuth_offset: 0
  # (float) offset of the orientation reference axis

  separate_positions: True
  # (bool) Flag to output processed images from separate positions in separate folders.

plotting:
  normalize_color_images: True
  # (bool) Scale fluorescence channels in each 'Retardance+Fluorescence' differently for optimal contrast. Set False to apply same scale for all images.

  transmission_scaling: 1E4
  # (float) scaling factor of transmission channel

  retardance_scaling: 1E3
  # (float) scaling factor of retardance channel

  save_birefringence_fig: False
  # (bool) save figures showing different channels

  save_stokes_fig: False
  # (bool)

  save_polarization_fig: False
  # (bool)

  save_micromanager_fig: False
  # (bool)

# Default values of keys when not specified #
#===========================================#

#   positions: 'all'
#   z_slices: 'all'
#   timepoints: 'all'
#   output_channels: ['Brightfield', 'Retardance', 'Orientation', 'Polarization']
#   circularity: 'rcp'
#   background_correction: 'None'
#   flatfield_correction: False
#   azimuth_offset: 0
#   separate_positions: True
#   normalize_color_images: True
#   save_birefringence_fig: False
#   save_stokes_fig: False
#   transmission_scaling: 1E4
#   retardance_scaling: 1E3


