dataset:
    processed_dir: '/flexo/ComputationalMicroscopy/Projects/brainarchitecture'
    data_dir: '/flexo/ComputationalMicroscopy/SpinningDisk/RawData/brainarchitecture/2018_10_02_MouseBrainSlice'
    samples: ['SM_2018_1002_1633_1', 'SM_2018_1002_1640_1']
    positions: 'all'
    background: 'BG_2018_1002_1625_1'

processing:
    output_channels: ['Transmission', 'Retardance', 'Orientation', 'Polarization']
    circularity: 'rcp'
    background_correction: 'Input'
    flatfield_correction: False
    azimuth_offset: 0
    separate_positions: True # Output processed images from separate positions in separate folders.    
plotting:
    normalize_color_images: True
    save_birefringence_fig: False
    save_stokes_fig: False
    save_polarization_fig: False
    save_micromanager_fig: False

# description of key-value pairs in the configuration file #
#==========================================================#

# samples:
#   a string, e.g. 'Sample1'
#   a list of samples, e.g. ['Sample1', 'Sample2']

# positions:
#   'all'
#   ['Pos1', 'Pos2', 'Pos3']
#   ['all', ['Pos1', 'Pos2']], in which case all positions from Sample1 and
#       Pos1 and Pos2 from Sample2 will be analyzed

# background:
#   a string, e.g. 'Background1', in which case all samples will be analyzed
#       with the same background data;
#   a list, e.g. ['Background1', 'Background2'], of one background dataset per sample


# background_correction:
#   'None': no background correction will be performed
#   'Input': user-provided background will be removed from sample data
#   'Local_filter': sample is first corrected with background provided in dataset section. The residual background is further removed with 'rolling ball' background correction.
#   'Local_defocus': sample is corrected with out-of-focus image of the sample. Requires testing.
#   'Auto': background for each sample position is chosen from the metadata generated by Micro-Manager.

# output_channels:
#    'Transmission', 'Retardance', 'Orientation', 'Polarization',
#    'Orientation_x', 'Orientation_y',
#    'Pol_State_0', 'Pol_State_1', 'Pol_State_2', 'Pol_State_3', 'Pol_State_4',
#    'Stokes_0', 'Stokes_1', 'Stokes_2', 'Stokes_3',
#    '405', '488', '568', '640',
#    'Retardance+Orientation', 'Polarization+Orientation',
#    'Transmission+Retardance+Orientation',
#    'Retardance+Fluorescence', 'Retardance+Fluorescence_all'

# circularity:
#    'rcp' and 'lcp' for right- and left-hand circular analyzers, respectively


# Default values of keys when not specified #
#===========================================#

#   positions: 'all'
#   output_channels: ['Transmission', 'Retardance', 'Orientation', 'Polarization']
#   circularity: 'rcp'
#   background_correction: 'None'
#   flatfield_correction: False
#   azimuth_offset: 0
#   separate_positions: True
#   normalize_color_images: True
#   save_birefringence_fig: False
#   save_stokes_fig: False

