dataset:
    data_dir: '/flexo/ComputationalMicroscopy/Projects/virtualstaining/testDataReconstructOrder/raw/2019_04_02_U2OS_plin2_SirActin_MTs'
    processed_dir: '/flexo/ComputationalMicroscopy/Projects/virtualstaining/testDataReconstructOrder/processed/'
    samples: ['2019-4-2-U2OS_plin2_DS1_2']
    background: 'BG_2019_0402_1052_1'
    positions: '4-Pos_000_000'

processing:
    output_channels: ['488', '568']
    circularity: 'rcp'
    background_correction: 'Local_filter'
    flatfield_correction: False
    azimuth_offset: 0
    n_slice_local_bg: 4
    
plotting:
    normalize_color_images: True
    save_birefringence_fig: False
    save_stokes_fig: False
    save_polarization_fig: False
    save_micromanager_fig: False
    
       

