dataset:
    RawDataPath: '/flexo/ComputationalMicroscopy/SpinningDisk/RawData/brainarchitecture'
    ProcessedPath: '/flexo/ComputationalMicroscopy/Processed/brainarchitecture'
    ImgDir: '2018_10_02_MouseBrainSlice'
    SmDir: ['SM_2018_1002_1633_1', 'SM_2018_1002_1640_1']
    BgDir: 'BG_2018_1002_1625_1'
    BgDir_local: None
processing:
    outputChann: ['Transmission', 'Retardance', 'Orientation', 'Scattering', 'Retardance+Orientation',
                   'Transmission+Retardance+Orientation', 'Scattering+Orientation', 'Retardance+Fluorescence',
                   '405', '568', '640']
    circularity: 'lcp'
    bgCorrect: 'Input'
    flatField: False
    batchProc: False
    azimuth_offset: 0
plotting:
    norm: True
    save_fig: False
       

