dataset:
    RawDataPath: '/flexo/ComputationalMicroscopy/SpinningDisk/RawData/brainarchitecture'
    ProcessedPath: '/flexo/ComputationalMicroscopy/Projects/brainarchitecture'
    ImgDir: '2018_10_02_MouseBrainSlice'
    SmDir: ['SM_2018_1002_1633_1', 'SM_2018_1002_1640_1']
    PosList: 'all'
    BgDir: 'BG_2018_1002_1625_1'
    PosList: 'all'
    BgDir_local: None
    separate_pos: True

processing:
    outputChann: ['Transmission', 'Retardance', 'Orientation', 'Polarization', 'Retardance+Orientation',
                   'Transmission+Retardance+Orientation', 'Scattering+Orientation', 'Retardance+Fluorescence',
                   '405', '568', '640']
    circularity: 'rcp'
    bgCorrect: 'Input'
    flatField: False
    batchProc: False
    azimuth_offset: 0
plotting:
    norm: True
    save_fig: False
    save_stokes_fig: False
    save_pol_fig: False
       

