dataset:
    data_dir: '/flexo/ComputationalMicroscopy/Projects/virtualstaining/testDataReconstructOrder/raw/2018_10_02_MouseBrainSlice'
    processed_dir: '/flexo/ComputationalMicroscopy/Projects/virtualstaining/testDataReconstructOrder/processed'
    samples: ['SM_2018_1002_1633_1','SM_2018_1002_1640_1']
    background: 'BG_2018_1002_1625_1'
    positions: 'Pos0'

processing:
    output_channels: ['Transmission', 'Retardance', 'Orientation', 'Polarization']
    circularity: 'rcp'
    background_correction: 'Input'
    flatfield_correction: False
    azimuth_offset: 0
    
plotting:
    normalize_color_images: True
    save_birefringence_fig: False
    save_stokes_fig: False
    save_polarization_fig: False
    save_micromanager_fig: False
    
       

